FROM postgres:15 as data-image

COPY ./data/ga_hits.csv ./data/ga_sessions.csv /usr/data/
COPY ./db-init/01-init.sql ./db-init/02-init.sh /docker-entrypoint-initdb.d/
COPY ./db-init/00-postgres-init.sh .

RUN chown -R postgres:postgres /usr/data

ARG POSTGRES_USER \
    POSTGRES_PASSWORD \
    POSTGRES_DB

RUN ["/bin/bash", "-c", "./00-postgres-init.sh postgres"]

FROM postgres:15

COPY --from=data-image ${PGDATA} ${PGDATA}

VOLUME ./data/postgres:/var/lib/postgresql/data
